Remove paramiko upper-bound
juju/python-libjuju pull request #1005
Opened 2024-01-09 10:01 UTC by gboutry

#### Description

*\<Please add why this change is needed and what it does.\>*
This change removes paramiko upper bound, allow using paramiko >3.0

*\<Fixes: #1004 \>*

#### QA Steps

*\<Commands / tests / steps to run to verify that the change works:\>*

```
tox -e py3 -- tests/unit/...
```

```
tox -e integration -- tests/integration/test_model.py::test_add_manual_machine_ssh
tox -e integration -- tests/integration/test_model.py::test_add_manual_machine_ssh_root
```

All CI tests need to pass.

#### Notes & Discussion

I've had to pin `urllib3` to `urllib3==1.25.7` to have the test pass. but the error was from pylxd failing with `TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'`. Not sure this is related to paramiko change, since paramiko does not depend on urllib3.

```
File "/home/gboutry/python-libjuju/tests/integration/test_model.py", line 596, in test_add_manual_machine_ssh
    await add_manual_machine_ssh(event_loop, is_root=False)
  File "/home/gboutry/python-libjuju/tests/integration/test_model.py", line 463, in add_manual_machine_ssh
    client = pylxd.Client()
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/pylxd/client.py", line 383, in __init__
    response = self.api.get()
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/pylxd/client.py", line 192, in get
    response = self.session.get(self._api_endpoint, *args, **kwargs)
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/gboutry/python-libjuju/.tox/py3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```

2024-01-09 21:36 UTC, cderici requested changes
> I've had to pin urllib3 to urllib3==1.25.7 to have the test pass.

This is because the transitive dependency coming from `pylxd`. So, `pylxd` [wants urllib3 < 2](https://github.com/canonical/pylxd/blob/4ecdc7532f31b71f1b985cf3da84890f0f55ced7/setup.cfg#L25), but additionally it depends on `requests` library, and `requests` in turn [wants urllib3>=1.21.1,<3 ](https://github.com/psf/requests/blob/96b22fa18c00831656ee4b286bf1c9062459b00a/setup.cfg#L10), but pip's not gonna complain because to satisfy pylxd's initial constraint it chooses the `urllib==1.26.somthing`, however, tox doesn't care about any of these unless you tell it explicitly. I tried swapping [these lines](https://github.com/juju/python-libjuju/blob/2581b0ced1df6201c6b7fd8cc0b20dcfa9d97c51/tox.ini#L64-L65) to install pylxd first and I'm surprised that pip didn't seem to handle the dependency constraint (it chose the urllib>2).

Anyways I'm fine with the paramiko version change. When I fix the urllib3 versions on my local the tests seem to be passing. Let's just remove the urllib3 lines from the `tox.ini` and let the `pip install pylxd` install it as a dependency. That one already satisfies the `requests` library. So it'll be fine until the `requests` raises the floor for the `urllib3` to >= 2. Then we might need to deal with another macaroonbakery situtation with the pylxd guys :)

Thanks for the PR <3

2024-01-10 15:58 UTC, cderici commented
/build

2024-01-10 16:47 UTC, gboutry commented
I think we'll need to put an upper limit on urllib3

2024-01-10 17:37 UTC, cderici commented
Yeah I'm not sure why we keep picking `urllib3=2.1.0`, let's see what it'll pick with the upper bound

2024-01-10 18:30 UTC, cderici approved these changes
Yeah that seems to have done it 👍

2024-01-10 20:19 UTC, cderici commented
/build

2024-01-10 20:36 UTC, cderici commented
/merge

2024-01-10 20:40 UTC, merged