Make consume respect the controller name in the url
juju/python-libjuju pull request #1038
Opened 2024-03-27 21:20 UTC by Aflynn50

#### Description

`consume` takes a `controller_name` argument. This is not needed and should be automatically generated from the offer url. A deprecation warning is logged and the variable is not used.

Also update offer and consume integration tests to no longer be skipped.

This helps avoid #1031 

#### QA Steps
```
juju bootstrap lxd c1
juju add-model offerer
juju deploy juju-qa-dummy-source dummy-source
juju offer dummy-source:sink
juju bootstrap lxd c2
python -m asyncio
# In repl:
from juju import model
m = model.Model()
await m.connect()
await m.consume("c1:admin/offerer.dummy-source")
```
*\<Commands / tests / steps to run to verify that the change works:\>*

```
tox -e py3 -- tests/unit/...
```

```
tox -e integration -- tests/integration/...
```

All CI tests need to pass.

*\<Please note that most likely an additional test will be required by the reviewers for any change that's not a one liner to land.\>*

#### Notes & Discussion

*\<Additional notes for the reviewers if needed. Please delete section if not applicable.\>*

2024-03-28 23:06 UTC, cderici requested changes
Code looks good. Could you please check if there's a test with a controller name in the endpoint url? If not we should add that (for `parse_offer_url`, or `_get_source_api`) I'd be ok if it's a mocked test within `tests/unit` if coming up with a sensible integration test is hard. We just need to ensure the capability is there for future. Hope that makes sense.

Also looks like we need a rebase.

2024-03-28 23:06 UTC, cderici commented on tests/integration/test_crossmodel.py
> +            await model_1.remove_offer("admin/{}.influxdb".format(model_1.name), force=True)
linter must be not happy with this change :)

2024-04-02 11:57 UTC, Aflynn50 commented
> Code looks good. Could you please check if there's a test with a controller name in the endpoint url? If not we should add that (for `parse_offer_url`, or `_get_source_api`) I'd be ok if it's a mocked test within `tests/unit` if coming up with a sensible integration test is hard. We just need to ensure the capability is there for future. Hope that makes sense.
> 
> Also looks like we need a rebase.

I've added a unit test which checks the consume behavior, though its uses a lot of mocks.

I've also changed it so you can use the controller_name argument as expected, just to ensure that we don't break anything with this.

2024-04-02 16:24 UTC, cderici approved these changes
Yeah this looks good 👍 mocking is fine as we can't bootstrap, the purpose of the test is just to protect the api in the future.

2024-04-02 16:24 UTC, cderici commented on tests/unit/test_offerendpoint.py
> +        """ Test consuming an offer an external controller. This would be better
```suggestion
        """ Test consuming an offer by an external controller. This would be better
```

2024-04-03 15:52 UTC, Aflynn50 commented
/merge

2024-04-03 15:55 UTC, merged