Enable attachment of binary files as charm resources
juju/python-libjuju pull request #1147
Opened 2024-10-08 19:20 UTC by nrobinaubertin

#### Description

This enables the attachment of binary files as charm resources.

Fixes: https://github.com/juju/python-libjuju/issues/1000

2024-10-09 02:03 UTC, dimaqq commented on juju/model.py
> +        headers['Content-Sha384'] = hashlib.sha384(data).hexdigest()
This effectively changes the argument type from `str` to `bytes`.

There's one more call site at line 2141 that would have to be updated to match.

P.S. please add an explicit type hint on the argument.

2024-10-09 07:44 UTC, dimaqq commented
@nrobinaubertin this PR needs some kind of test.

ideally an integration test, or 
a series of steps (this exact charm, this bootstrap, this deploy with this binary artifact)

2024-10-10 09:35 UTC, gfouillet requested changes
Nothing to more than dima.

* Please add a test that would trigger the bug if not fixed
* take care of all call site of `_upload` to ensure `data` type consistency.

2024-11-08 03:35 UTC, dimaqq commented
Niels, I see that the PR where you needed this was closed.

Do you have the bandwidth to update this PR?

If not, I can maybe create an issue based on the PR and eventually someone else can pick this up. What you're fixing is basically a bug, as binary resources should be supported.

2024-11-19 06:59 UTC, dimaqq commented
This PR needs to be rebased since #1186 has been merged.

2024-11-20 00:26 UTC, nrobinaubertin commented
> Do you have the bandwidth to update this PR?

Not right now, so if you feel we should close this PR, we can do it and I may reopen it later.

> If not, I can maybe create an issue based on the PR and eventually someone else can pick this up. What you're fixing is basically a bug, as binary resources should be supported.

There is already an issue, #1000

2024-11-26 05:03 UTC, dimaqq commented
- rebased
- fixed the yaml code path
- added type hints

2024-11-26 05:03 UTC, dimaqq commented on juju/model.py
> +        headers['Content-Sha384'] = hashlib.sha384(data).hexdigest()
done now

2024-11-26 06:05 UTC, dimaqq commented
Moved to #1218

2024-11-26 06:05 UTC, closed without merging