docs: move docs from juju.is
juju/python-libjuju pull request #1244
Opened 2024-12-18 16:00 UTC by tmihoc

As part of a broader move where juju.is docs go federated and RTD, this PR adds all the python-libjuju material we previously had under juju.is/docs/juju (in how-to guide tabs) to the python-libjuju RTD (under a new section called "How-to guides").

This RTD project could use a lot of further improvements (e.g., for all of the other projects -- juju, terraform-provider-juju, charmcraft, ops -- I made sure to update the homepage according to the standard template and to have the full Diataxis tree and integrate the new content nicely with the old, removing duplication, etc.). However, given that we are slowly phasing python-libjuju out, I believe leaving things as is is probably fine.

There is one fix that it is worth making, namely, the links to Juju docs. I followed the instructions in https://canonical-documentation-with-sphinx-and-readthedocscom.readthedocs-hosted.com/style-guide/#internal-references for "targets in other doc sets", but the links don't seem to be working. It could be because the Juju RTD project needs some fixing (we're working on it). I should know soon enough what needs to be done and then I'll come back and fix all the links in a follow-up PR.

#### QA Steps

From the root of the repo:

```
# Build the docs:
tox -e docs 

#Preview the docs:
open docs/_build/index.html
```

2024-12-18 19:30 UTC, benhoyt requested changes
Thanks for this, @tmihoc! However, it looks like you've accidentally commits all the Python files under `build/*`. Where are these files coming from? Should the `/build` directory be added to `.gitignore`?

2024-12-18 19:30 UTC, benhoyt commented on docs/howto/#manage-machines.rst#
> +.. _manage-machines:
Is this `#manage-machines.rst#` file an editor backup? Presumably it shouldn't be committed.

2024-12-19 04:54 UTC, james-garner-canonical commented
I've taken care of rebasing this branch, and added a commit that removes `build/` and `#manage-machines.rst#`, updates `.gitignore` to ignore `build/`, and adds the (mostly whitespace) changes mandated by `pre-commit`.

2024-12-19 06:06 UTC, tonyandrewmeyer approved these changes
This makes sense to me. The how-to guides are integrated, which is the main point, and while the docs site is still not great, I agree that it doesn't make sense to fix that given where things are headed.

For the broken Juju docs, the plan to fix them in a future PR seems fine - I don't think it needs to block merging, even though we did that that approach with ops. For what it's worth, I don't see the `juju` cross-Sphinx link defined, so that may be the problem?

2024-12-19 06:51 UTC, dimaqq reviewed
first read

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-applications.rst
> +   await my_app.set_constraints(constraints={, 'arch': 'amd64', 'mem': 256})
```suggestion
   await my_app.set_constraints(constraints={'arch': 'amd64', 'mem': 256})
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-applications.rst
> +   await my_model.deploy(..., constraints={, 'arch': 'amd64', 'mem': 256}, ...)
```suggestion
   await my_model.deploy(..., constraints={'arch': 'amd64', 'mem': 256}, ...)
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-storage-pools.rst
> +       attributes={"volume-type":"provisioned-iops", "iops"="40"})
```suggestion
       attributes={"volume-type": "provisioned-iops", "iops": "40"})
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-credentials.rst
> +       jujuclient.CloudCredential(auth_type="jsonfile", attrs={'file':'path_to_cred_file'})
```suggestion
   my_controller.add_credential("my-credential",
       jujuclient.CloudCredential(auth_type="jsonfile", attrs={'file':'path_to_cred_file'}))
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-ssh-keys.rst
> +> See more: `add_ssh_key() `https://pythonlibjuju.readthedocs.io/en/latest/api/juju.model.html#juju.model.Model.add_ssh_key>`_, `Model (module) <https://pythonlibjuju.readthedocs.io/en/latest/narrati
```suggestion
> See more: `add_ssh_key() https://pythonlibjuju.readthedocs.io/en/latest/api/juju.model.html#juju.model.Model.add_ssh_key>`_, `Model (module) <https://pythonlibjuju.readthedocs.io/en/latest/narrative/model.html>`_
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-storage.rst
> +> See more: `detach_storage() <https://pythonlibjuju.readthedocs.io/en/latest/api/juju.unit.html#juju.unit.Unit.detach_storage>`_, `Unit (module) <https://pythonlibjuju.readthedocs.io/en/latest/narra
```suggestion
> See more: `detach_storage() <https://pythonlibjuju.readthedocs.io/en/latest/api/juju.unit.html#juju.unit.Unit.detach_storage>`_, `Unit (module) <https://pythonlibjuju.readthedocs.io/en/latest/narrative/unit.html>`_
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-secret-backends.rst
> +> See more: `add_secret_backend() <https://pythonlibjuju.readthedocs.io/en/latest/api/juju.controller.html#juju.controller.Controller.add_secret_backends>`_, `Controller (module) <https://pythonlibju
```suggestion
> See more: `add_secret_backends() <https://pythonlibjuju.readthedocs.io/en/latest/api/juju.controller.html#juju.controller.Controller.add_secret_backends>`_, `Controller (module) <https://pythonlibjuju.readthedocs.io/en/latest/narrative/controller.html>`_
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-secret-backends.rst
> +> See more: `update_secret_backend() <https://pythonlibjuju.readthedocs.io/en/latest/api/juju.controller.html#juju.controller.Controller.update_secret_backends>`_, `Controller (module) <https://pytho
```suggestion
> See more: `update_secret_backends() <https://pythonlibjuju.readthedocs.io/en/latest/api/juju.controller.html#juju.controller.Controller.update_secret_backends>`_, `Controller (module) <https://pythonlibjuju.readthedocs.io/en/latest/narrative/controller.html>`_
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-units.rst
> +Too see details about a unit in `python-libjuju` client, you can use various fields and methods of a `Unit` object. For example, to get the `public_address` of a unit:
```suggestion
To see details about a unit in `python-libjuju` client, you can use various fields and methods of a `Unit` object. For example, to get the `public_address` of a unit:
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-storage.rst
> +
```suggestion
   await my_unit.detach_storage("osd-devices/2")

```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-units.rst
> +> See more: `Unit.resolved()`
```suggestion
   await my_unit.resolved()

> See more: `Unit.resolved() https://pythonlibjuju.readthedocs.io/en/latest/api/juju.unit.html#juju.unit.Unit.resolved`_
```

2024-12-19 06:51 UTC, dimaqq commented on docs/howto/manage-users.rst
> +You can also check if a user is enabled or disabled using the `enabled` and `disabled` properties on the Unit object.
```suggestion
You can also check if a user is enabled or disabled using the `enabled` and `disabled` properties on the User object.
```

2024-12-19 12:30 UTC, tmihoc commented
@james-garner-canonical I see you've already committed some improvements. Do you think I could leave this PR in your hands? Asking because I'm juggling changes in a few other repos at the moment and I could use all the help I can get.

2024-12-19 21:51 UTC, james-garner-canonical commented
I've merged @dimaqq's suggestions and signed the commit.

Re: linking to Juju docs, @tonyandrewmeyer's comment pointed me to us needing to define the `juju:` reference for sphinx. [intersphinx](https://docs.readthedocs.io/en/stable/guides/intersphinx.html) is already in `docs/conf.py`'s `extensions`, so I guess we need something like this -- but what url do we use here?

```py
intersphinx_mapping = {
    "juju": (JUJU_DOCS_URL, None),
}
```

2024-12-19 22:04 UTC, james-garner-canonical commented
I guess if we go with @tmihoc's original suggestion to fix the Juju links in a subsequent PR, then this might be ready to merge. Any objections, @benhoyt and @dimaqq ?

2024-12-19 22:21 UTC, benhoyt approved these changes
Yep, I'm good with it.

The only minor thing I noticed when viewing locally is the breadcrumbs at the top of the page have a "<no-title>" in them:
![Screenshot from 2024-12-20 11-21-20](https://github.com/user-attachments/assets/ae759c59-7736-4e07-9ed5-58f94fa19656)

2024-12-20 00:57 UTC, james-garner-canonical commented
/merge

2024-12-20 01:00 UTC, merged