Implement add_space and get_spaces
juju/python-libjuju pull request #467
Opened 2021-01-30 12:56 UTC by gnuoy

This PR implements add_space and get_spaces. Since spaces are not
implemented with the LXD provider there is not corresponding
functional test. Closes issue #466.

2021-01-30 16:51 UTC, SimonRichardson requested changes
@manadart can you check this as well 👍

2021-01-30 16:51 UTC, SimonRichardson commented on juju/client/connection.py
> +    'Spaces': {'versions': [2, 3, 6]},
Can you add, `4, 5` as well to this.

2021-02-01 08:55 UTC, SimonRichardson approved these changes
Let's good from my perspective.

2021-02-01 09:06 UTC, manadart approved these changes
Looks good.

2021-02-01 09:07 UTC, SimonRichardson commented
!!build!!

2021-02-01 09:10 UTC, SimonRichardson commented
@gnuoy can you fix the lint issues, then I can land it.

> juju/tag.py:54:1: E302 expected 2 blank lines, found 1

2021-02-01 09:33 UTC, SimonRichardson commented
!!build!!

2021-02-01 09:54 UTC, SimonRichardson commented
$$merge$$

2021-02-01 10:07 UTC, SimonRichardson commented
$$merge$$

2021-02-01 10:17 UTC, SimonRichardson commented
$$merge$$

Failed to build python 3.5, considering it's EOL (#468) we should remove.

2021-02-01 10:22 UTC, merged