Add local resources support for oci-images
juju/python-libjuju pull request #486
Opened 2021-04-15 12:21 UTC by DomFleischmann

This commit enables support for local resources of the oci-image type.

This will address issue #472 .

2021-04-21 15:06 UTC, johnsca requested changes
There are some fixes that need to be made in the test, but the code itself LGTM.

2021-04-21 15:06 UTC, johnsca commented on tests/integration/oci-image-charm/dispatch
> +status-set active
I'm not certain that it wouldn't be better to have the `waiting` status be `blocked` instead. On the one hand, I don't want this to get stuck in `waiting`, but on the other, I feel (without any real evidence) like there's a chance that early hooks might have the controller fail on the `resource-get` even if the resource is provided with the deploy call and then have it succeed on a later hook.

2021-04-21 15:06 UTC, johnsca commented on tests/integration/oci-image-charm/metadata.yaml
> +    auto-fetch: true
This doesn't do anything and should be dropped. (It is used by a helper library in reactive charms, but that's not applicable here.)

2021-04-26 13:25 UTC, johnsca approved these changes

2021-04-26 13:25 UTC, johnsca commented
!!build!!

2021-04-26 14:30 UTC, johnsca requested changes

2021-04-26 14:30 UTC, johnsca commented on tests/integration/test_model.py
> +    tests_dir = Path(__file__).absolute().parent.parent
```suggestion
    tests_dir = Path(__file__).absolute().parent
```

2021-04-26 14:34 UTC, johnsca approved these changes

2021-04-26 14:37 UTC, johnsca commented
Integration tests are still failing due to the snapd profile issue, not relevant to this change.  I confirmed locally that the added test works.

2021-04-26 14:40 UTC, SimonRichardson approved these changes

2021-04-26 14:40 UTC, SimonRichardson commented
$$merge$$

2021-04-26 15:18 UTC, SimonRichardson commented
!!build!!

2021-04-26 15:18 UTC, SimonRichardson commented
Just fighting with CI atm, sorry for the noise.

2021-04-26 17:36 UTC, SimonRichardson commented
!! build!!

2021-04-27 09:32 UTC, SimonRichardson commented
!!build!!

2021-04-27 09:46 UTC, SimonRichardson commented
$$merge$$

2021-04-27 09:52 UTC, merged