Provide extra metadata with charmstore.entity(...)
juju/python-libjuju pull request #635
Opened 2022-02-10 22:04 UTC by addyess

some API's responses were lost during the transition to charmhub api responses.  To restore the api of python-libjuju wrap those API responses in a new method

2022-02-10 22:05 UTC, addyess commented
Addresses https://github.com/juju/python-libjuju/issues/634

2022-02-10 22:08 UTC, addyess commented on juju/charmstore.py
> +
this wraps `theblues.charmstore.Charmstore` entity method by giving it resources super powers as well as including the 'id' query parameter which emits an extra `Id` field under the `Meta` section

2022-02-10 22:10 UTC, addyess commented on juju/charmstore.py
> +            attr = getattr(self._cs, name)
if `entity` attribute is requested, provide the overloaded `_entity` method

2022-02-10 22:13 UTC, addyess commented on juju/model.py
> +
charmhub api will never again return `charm-metadata`.  maybe its silly to even support this.  until the day someone say "turn it back on".

2022-02-10 22:19 UTC, johnsca approved these changes
LGTM

2022-02-10 22:48 UTC, wallyworld approved these changes
Looks ok to me.
@SimonRichardson can you look also?

2022-02-11 08:30 UTC, SimonRichardson commented
!!build!!

Not sure why the builds were aborted.

2022-02-11 11:29 UTC, SimonRichardson requested changes
As I can't push to your branch, I've opened #636, you can steal that commit, or we can work on it there. Either way.

2022-02-11 14:08 UTC, addyess commented
@SimonRichardson -- i cherry-picked your commit

2022-02-11 14:36 UTC, SimonRichardson approved these changes

2022-02-11 16:42 UTC, SimonRichardson commented
$$merge$$

2022-02-11 16:45 UTC, merged